### ISSUE TITLE
Add Bower Support + Angular Directives

### ISSUE THREAD

**Issue by lbenie** [vukhanhtruong/jquery-elastic-grid#7]
Adding a bower package and an angular.js directive.

They could be really useful for developping projects

**Comment by lbenie** [comment]
@vukhanhtruong 

I have created an angular directive wrapper for this library
you can check it out [here](https://github.com/lbenie/angular-elastic-grid)

**Comment by vukhanhtruong** [comment]
Hi,
Thanks, you did a great job. 
Regards,
